### ISSUE TITLE
Request for FreeCAD Files

### ISSUE THREAD

**Issue by weissalec05** [thethoughtemporium/sputteringsystem#2]
Hi @the-thought-emporium ,

I hope this message finds you well. I'm really interested in your project and was hoping to dive into the design files you've shared on GitHub. However, I noticed that the repository contains .step files instead of the FreeCAD source files.

If possible, could you share the FreeCAD files for this project? It would be extremely helpful, as I'd like to explore the original designs and make modifications within FreeCAD.

Thanks in advance for your help, and I look forward to hearing from you soon.

Best regards,

Alec Weiß

**Comment by novelastresol** [comment]
Hello the .step files are Universal files and usable with freeCAD/fusion360 or any other software you use
